[package]
name = "heng_rs_example"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
heng_rs = { path = "../../", default-features = false, features = ["with-async-std"] }
async-std = { version = "1.5.0", features = ["unstable", "attributes"] }